//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GutsyPuppet.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GutsyPuppetEntities : DbContext
    {
        public GutsyPuppetEntities()
            : base("name=GutsyPuppetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuthUserLogin> AuthUserLogins { get; set; }
        public virtual DbSet<AuthUser> AuthUsers { get; set; }
        public virtual DbSet<AuthUserSetting> AuthUserSettings { get; set; }
        public virtual DbSet<OnTimeItem> OnTimeItems { get; set; }
        public virtual DbSet<TeamUser> TeamUsers { get; set; }
        public virtual DbSet<TimeUnitType> TimeUnitTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserSecurityRole> UserSecurityRoles { get; set; }
        public virtual DbSet<UserToken> UserTokens { get; set; }
        public virtual DbSet<WorkflowStep> WorkflowSteps { get; set; }
        public virtual DbSet<WorkLog> WorkLogs { get; set; }
    }
}
