//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GutsyPuppet.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeUnitType
    {
        public int TimeUnitTypeId { get; set; }
        public string Name { get; set; }
        public string Abbreviation { get; set; }
        public int DisplayOrder { get; set; }
        public int ConversionFactor { get; set; }
    }
}
