//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GutsyPuppet.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string LoginId { get; set; }
        public string Password { get; set; }
        public string WindowsId { get; set; }
        public bool UseWindowsAuth { get; set; }
        public bool BuiltInAccount { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> LastLoginDateTime { get; set; }
        public byte[] ReadMessages { get; set; }
        public string NewSettingsXml { get; set; }
        public bool IsLocked { get; set; }
        public int FailedLogins { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string HashData { get; set; }
        public byte[] UserImage { get; set; }
        public bool UseGravatar { get; set; }
        public string EmailSignature { get; set; }
        public string CultureInfo { get; set; }
        public System.DateTime LastUpdatedDateTime { get; set; }
        public bool HasImage { get; set; }
    }
}
