//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GutsyPuppet.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowStep
    {
        public int WorkflowStepId { get; set; }
        public int WorkflowId { get; set; }
        public int StepOrder { get; set; }
        public string StepName { get; set; }
        public int EditFieldTemplateId { get; set; }
        public bool RequireEdit { get; set; }
        public bool ArchiveItem { get; set; }
        public bool SuppressNotifications { get; set; }
        public bool UpdateTimeEstimate { get; set; }
        public bool PromptWorkLogEntry { get; set; }
        public bool RequireWorkLogEntry { get; set; }
        public int NewEmailWorkflowStepId { get; set; }
        public Nullable<int> DefaultColor { get; set; }
        public bool UnarchiveItem { get; set; }
        public int SourceControlCommitWorkflowStepId { get; set; }
        public string Rules { get; set; }
        public bool EnableWIPLimits { get; set; }
        public int WIPItemsPerStep { get; set; }
        public bool EnforceWIPLimits { get; set; }
        public bool EnableWIPLimitsPerUser { get; set; }
        public bool EnforceWIPLimitsPerUser { get; set; }
        public int WIPItemsPerUser { get; set; }
        public Nullable<int> ItemCopyItemType { get; set; }
        public int CustomIntegrationId { get; set; }
    }
}
